name: panda_and_dragon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localization:
  google_fonts: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Kalam
      fonts:
        - asset: fonts/Kalam-Bold.ttf
        - asset: fonts/Kalam-Light.ttf
        - asset: fonts/Kalam-Regular.ttf
